import Sidebar from '@/components/main/sidebar';
import { Bookmark } from '@/models/bookmark';
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

async function getBookmarks(): Promise<Bookmark[]> {
  const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/api/bookmarks`, {
    cache: 'no-store',
  });
  if (!res.ok) {
    throw new Error('Failed to fetch bookmarks');
  }
  return res.json();
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const bookmarks = await getBookmarks();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex w-full">
          <Sidebar bookmarks={bookmarks} />
          <main className="flex-1">{children}</main>
        </div>
      </body>
    </html>
  );
}
